---
- name: Install php-fpm.conf
  template:
    src: php-fpm.conf.j2
    dest: /etc/php-fpm.conf

- name: Ensure PHP packages are installed.
  package:
    name: "{{ item }}"
    state: "{{ php_packages_state }}"
    enablerepo: "{{ php_enablerepo }}"
  with_items: "{{ php_packages }}"
  notify: restart webserver
